server {
  listen 80;

  location = /nginx-health {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
  }

  location /api/ {
    proxy_pass http://backend:3000/;
  }

  location / {
    proxy_pass http://frontend:80;
  }
}
